enabledworlds:
  - 'world'
  - 'world_the_end'
  - 'world_nether'
  - 'donor'
commandprefix: '&6[&eMG&6]&f'
dwarfhealth: 24
elfhealth: 20
demonhealth: 22
humanhealth: 26
enderbornhealth: 22
altarblock: 133
altarsecondblock: 155
altarsecondblockamount: 9
altarsecondblockradius: 6
cureitems:
  - '264:10'
  - '89:10'
  - '98:64'
demonchant: 'Enemies of the fire shall perish, I bind my soul in flames!'
bleedchance: 6
bleeddamage: 1
bleedduration: 3
waterdamage: 1
dwarfadditionalarrowdamage: 2
axeadditionaldamage: 3
bowadditionaldamage: 2
elffiredamage: 1
battlecrystrength: 2.0
battlecrycooldown: 30