main: com.minegusta.mgraces.Main
name: MGRaces
authors: [janie177, xSoccerManX]
version: ${project.version}
commands:
   race:
      aliases: [races, class, classes, ra, rc]
      usage: /Race
      description: All information you need about races.
